packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"
  - "@swc/core"
  - "@medusajs/telemetry"
  - "msgpackr-extract"
  - "protobufjs"
